name: PHP Composer


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Yii2 (PHP ${{ matrix.php-versions }})
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      TEST_DB_USERNAME: root
      TEST_DB_PASSWORD: root
      DB_CHARSET: utf8
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_DATABASE: yii2_basic_tests
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start mysql service
      run: sudo /etc/init.d/mysql start

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 32574 -uroot -proot -e "SHOW DATABASES"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Run test suite
      run: |
        vendor/bin/codecept build
        vendor/bin/codecept run functional
