name: PHP Composer


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Yii2 (PHP ${{ matrix.php-versions }})
    env:
      DB_USERNAME: root
      DB_PASSWORD:
      TEST_DB_USERNAME: root
      TEST_DB_PASSWORD:
      DB_CHARSET: utf8
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: yii2_basic_tests
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Run test suite
      run:
        vendor/bin/codecept build
        vendor/bin/codecept run functional
